services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DEFAULT_HOST: hikinamuri.ru

  letsencrypt:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: hikinamuri@mail.ru


  backend:
    build:
      context: .
    command: python ./src/back/app.py
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: hikinamuri.ru

  frontend:
    build:
      context: .
    command: npm run dev
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: hikinamuri.ru